channels:
  - nvidia/label/cuda-12.3.2
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3
  - binutils_impl_linux-64=2.40
  - blas=1.0
  - clapack=3.2.1
  - cuda=12.3.2
  - cuda-cccl
  - cuda-cccl_linux-64
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-crt-dev_linux-64
  - cuda-cudart
  - cuda-cudart-dev
  - cuda-cudart-dev_linux-64
  - cuda-cudart-static
  - cuda-cudart-static_linux-64
  - cuda-cudart_linux-64
  - cuda-cuobjdump
  - cuda-cupti
  - cuda-cupti-static
  - cuda-cuxxfilt
  - cuda-demo-suite
  - cuda-documentation
  - cuda-driver-dev
  - cuda-gdb
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-libraries-static
  - cuda-nsight
  - cuda-nsight-compute
  - cuda-nvcc
  - cuda-nvdisasm
  - cuda-nvml-dev
  - cuda-nvprof
  - cuda-nvprune
  - cuda-nvrtc
  - cuda-nvrtc-dev
  - cuda-nvrtc-static
  - cuda-nvtx
  - cuda-nvvp
  - cuda-opencl
  - cuda-opencl-dev
  - cuda-profiler-api
  - cuda-runtime
  - cuda-sanitizer-api
  - cuda-toolkit
  - cuda-tools
  - cuda-version
  - cuda-visual-tools
  - cudnn
  - fftw
  # - openmpi
  - gcc=12.4.0
  - gcc_impl_linux-64=12.4.0
  - gds-tools
  - gxx=12.4.0
  - gxx_impl_linux-64=12.4.0
  - kernel-headers_linux-64
  - ld_impl_linux-64
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas
  - libcublas-dev
  - libcublas-static
  - libcufft
  - libcufft-dev
  - libcufft-static
  - libcufile
  - libcufile-dev
  - libcufile-static
  - libcurand
  - libcurand-dev
  - libcurand-static
  - libcusolver
  - libcusolver-dev
  - libcusolver-static
  - libcusparse
  - libcusparse-dev
  - libcusparse-static
  - libgcc=14.2.0
  - libgcc-devel_linux-64=12.4.0
  - libgcc-ng=14.2.0
  - libgfortran-ng
  - libgfortran4
  - libgfortran5
  - libgomp
  - liblapack
  - liblapacke
  - libnpp
  - libnpp-dev
  - libnpp-static
  - libnvjitlink
  - libnvjitlink-dev
  - libnvjpeg
  - libnvjpeg-dev
  - libnvjpeg-static
  - libopenblas
  - libpng
  - libsanitizer
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=12.4.0
  - libstdcxx-ng=14.2.0
  - make
  - mpi
  - mpich
  - nomkl
  - nsight-compute
  - openblas
  - openblas-devel
  - sysroot_linux-64
  - tzdata
  - zlib
